polls/urls.py
from django.urls import path, re_path

from . import views
app_name = 'polls'


urlpatterns = [
    path('', views.index, name='index'),   
    path('index', views.index, name='index'),
    path('qr_lists', views.qr_lists, name='qr_lists'),
    path('show_qr/<slug:slug>', views.show_qr, name='show_qr'),
    path('show_barcode/<slug:slug>', views.show_barcode, name='show_barcode'),
    path('create_qr', views.create_qr, name='create_qr'),
    path('barcode_view', views.barcode_view, name='barcode_view'),
    path('create_barcode', views.create_barcode, name='create_barcode'),
    


]

qr_code_generate/urls.py
from django.contrib import admin
from django.urls import include, path,re_path

from polls.views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('polls.urls',namespace="index") ),
    path('barcode_view', include('polls.urls',namespace="barcode_view")),  
    path('create_qr', include('polls.urls',namespace="create_qr")),  
    path('create_barcode', include('polls.urls',namespace="create_barcode")),  
    path('qr_lists', include('polls.urls',namespace="qr_lists")),  
    path('show_qr', include('polls.urls',namespace="show_qr")),  
]

polls/models.py
from django.db import models


class QR(models.Model):

    id = models.AutoField(auto_created=True, primary_key=True, serialize=False)
    sampled_by = models.CharField(max_length=250, verbose_name='Sampled by')
    unit = models.CharField(max_length=250, verbose_name='Unit')
    sample_point = models.CharField(max_length=250, verbose_name='Sample Point')
    sample_type = models.CharField(max_length=250, verbose_name='Sample Type')
    data_time = models.DateTimeField(auto_now=False, auto_now_add=False,  verbose_name='Date Time')
    hashing_name = models.CharField(max_length=250, verbose_name='Hash Name')
    
    #class Meta:
        #abstract = True

    def __str__(self):
        return self.hashing_name
    


class Barcode(models.Model):

    id = models.AutoField(auto_created=True, primary_key=True, serialize=False)
    sampled_by = models.CharField(max_length=250, verbose_name='Sampled by')
    unit = models.CharField(max_length=250, verbose_name='Unit')
    sample_point = models.CharField(max_length=250, verbose_name='Sample Point')
    sample_type = models.CharField(max_length=250, verbose_name='Sample Type')
    data_time = models.DateTimeField(auto_now=False, auto_now_add=False,  verbose_name='Date Time')
    hashing_name = models.CharField(max_length=250, verbose_name='Hash Name')
    
    #class Meta:
        #abstract = True

    def __str__(self):
        return self.hashing_name

polls/forms.py
from django import forms
from polls.models import *
from django.contrib import admin



class QR_Form(forms.ModelForm):
	
	class Meta:
		model = QR
		fields = '__all__'



class Barcode_Form(forms.ModelForm):
	
	class Meta:
		model = Barcode
		fields = '__all__'



admin.site.register(Barcode)
admin.site.register(QR)

polls/views.py
from django.shortcuts import render,redirect,HttpResponseRedirect
import segno
from hashlib import shake_256
import hashlib
from time import localtime
from pathlib import Path
import random
import numpy as np
from django.urls import reverse
from .forms import  *
from .models import *
from asgiref.sync import sync_to_async
import os
from barcode import EAN13 as brcode
from barcode.writer import ImageWriter
os.environ["DJANGO_ALLOW_ASYNC_UNSAFE"] = "true"

BASE_DIR = Path(__file__).resolve().parent.parent



def add_prefix2():   
    prefix = hashlib.sha1(f"{np.random.rand(50)}{localtime}".encode('utf-8')).hexdigest()
    return str(int(prefix, 16))[:13]  

def add_prefix():   
    prefix = shake_256(f"{np.random.rand(50)}{localtime}".encode('utf-8')).hexdigest(20)
    return prefix  

async def index(request):
    
    return render(request,"main.html",{})

async def barcode_view(request):

    query = Barcode.objects.all()
    
    return render(request,"barcode_view.html",{"query":query})

async def show_barcode(request,slug):
    
    return render(request,"show_barcode.html",{'slug':slug})

async def create_barcode(request):
    if request.method == 'POST':
        form = Barcode_Form(request.POST or None, request.FILES or None)
        
        if form.is_valid():           
                        
            sampled_by   = form.cleaned_data['sampled_by']
            unit         = form.cleaned_data['unit']
            sample_point = form.cleaned_data['sample_point']
            sample_type  = form.cleaned_data['sample_type']
            data_time    = form.cleaned_data['data_time']
            color        = request.POST.get('color')
            
            hash = add_prefix2()
            print(hash)
            bkbarcode = brcode(f'{hash}', writer=ImageWriter())
            bkbarcode.save(f"{BASE_DIR}/static/barcode_images/{hash}")
            
            form.instance.hashing_name = hash
            
            form.save()
            return redirect(f'/show_barcode/{hash}',hash,permanent=True)
    else:
        return render(request,"create_barcode.html",{})


async def qr_lists(request):
    
    query = QR.objects.all()
    
    
    return render(request,"qr_view.html",{"query":query})



async def show_qr(request,slug):
    
    return render(request,"show_qr.html",{'slug':slug})



async def create_qr(request):
    if request.method == 'POST':
        form = QR_Form(request.POST or None, request.FILES or None)
        
        if form.is_valid():           
                        
            sampled_by   = form.cleaned_data['sampled_by']
            unit         = form.cleaned_data['unit']
            sample_point = form.cleaned_data['sample_point']
            sample_type  = form.cleaned_data['sample_type']
            data_time    = form.cleaned_data['data_time']
            color        = request.POST.get('color')
            
            hash = add_prefix()
            qrcode = segno.make([{'sampled_by':sampled_by, 'unit':unit, 'sample_point':sample_point, 'sample_type':sample_type,'data_time':data_time}])
            qrcode.save(f"{BASE_DIR}/static/qr_images/{hash}.svg", scale=40,dark=color, light='#ffffff',)
            
            form.instance.hashing_name = hash
            
            form.save()
            return redirect(f'/show_qr/{hash}',hash,permanent=True)
    else:
        return render(request,"create_qr.html",{})

templates/dashboard.html
{% load static %}

        
{% include 'navbar.html' %} 
        
        
<div class="page-wrapper">
    <div class="container-xl">

        
        
        
        
        <!-- Page title -->
        <div class="page-header d-print-none">
            <div class="row align-items-center">
                <div class="col">
                    <!-- Page pre-title -->
                    <div class="page-pretitle">
                        Overview
                    </div>
                    <h2 class="page-title">
                        Dashboard
                    </h2>
                </div>
            </div>
        </div>
    </div>
    <div class="page-body">
        <div class="container-xl">
            <div class="row row-deck row-cards mb-5">
                
                                
                <div class="col-sm-6 col-lg-3">
                    <div class="card">
                        <a href="{% url 'polls:qr_lists' %}">
                            <div class="card-stamp">
                                <div class="card-stamp-icon bg-green">
                                    <svg xmlns="http://www.w3.org/2000/svg"
                                        class="icon icon-tabler icon-tabler-businessplan" width="24" height="24"
                                        viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none"
                                        stroke-linecap="round" stroke-linejoin="round">
                                        <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                                        <ellipse cx="16" cy="6" rx="5" ry="3"></ellipse>
                                        <path d="M11 6v4c0 1.657 2.239 3 5 3s5 -1.343 5 -3v-4"></path>
                                        <path d="M11 10v4c0 1.657 2.239 3 5 3s5 -1.343 5 -3v-4"></path>
                                        <path d="M11 14v4c0 1.657 2.239 3 5 3s5 -1.343 5 -3v-4"></path>
                                        <path d="M7 9h-2.5a1.5 1.5 0 0 0 0 3h1a1.5 1.5 0 0 1 0 3h-2.5"></path>
                                        <path d="M5 15v1m0 -8v1"></path>
                                    </svg>
                                </div>
                            </div>
                            <div class="card-body">
                                <div class="d-flex align-items-center mb-3">
                                    <div class="subheader">QR Codes</div>
                                </div>
                                <div class="h1">95</div>
                            </div>
                        </a>
                    </div>
                </div>

                
                <div class="col-sm-6 col-lg-3">
                    <div class="card">
                        <a href="{% url 'polls:create_qr' %}">
                            <div class="card-stamp">
                                <div class="card-stamp-icon bg-green">
                                    <svg xmlns="http://www.w3.org/2000/svg"
                                        class="icon icon-tabler icon-tabler-businessplan" width="24" height="24"
                                        viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none"
                                        stroke-linecap="round" stroke-linejoin="round">
                                        <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                                        <ellipse cx="16" cy="6" rx="5" ry="3"></ellipse>
                                        <path d="M11 6v4c0 1.657 2.239 3 5 3s5 -1.343 5 -3v-4"></path>
                                        <path d="M11 10v4c0 1.657 2.239 3 5 3s5 -1.343 5 -3v-4"></path>
                                        <path d="M11 14v4c0 1.657 2.239 3 5 3s5 -1.343 5 -3v-4"></path>
                                        <path d="M7 9h-2.5a1.5 1.5 0 0 0 0 3h1a1.5 1.5 0 0 1 0 3h-2.5"></path>
                                        <path d="M5 15v1m0 -8v1"></path>
                                    </svg>
                                </div>
                            </div>
                            <div class="card-body">
                                <div class="d-flex align-items-center mb-3">
                                    <div class="subheader">EPC QR Codes</div>
                                </div>
                                <div class="h1">1</div>
                            </div>
                        </a>
                    </div>
                </div>
                
                
                                
                <div class="col-sm-6 col-lg-3">
                    <div class="card">
                        <a href="{% url 'polls:barcode_view' %}">
                            <div class="card-body">
                                <div class="card-stamp">
                                    <div class="card-stamp-icon bg-green">
                                        <svg xmlns="http://www.w3.org/2000/svg"
                                            class="icon icon-tabler icon-tabler-calendar-stats" width="24"
                                            height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor"
                                            fill="none" stroke-linecap="round" stroke-linejoin="round">
                                            <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                                            <path
                                                d="M11.795 21h-6.795a2 2 0 0 1 -2 -2v-12a2 2 0 0 1 2 -2h12a2 2 0 0 1 2 2v4">
                                            </path>
                                            <path d="M18 14v4h4"></path>
                                            <circle cx="18" cy="18" r="4"></circle>
                                            <path d="M15 3v4"></path>
                                            <path d="M7 3v4"></path>
                                            <path d="M3 11h16"></path>
                                        </svg>
                                    </div>
                                </div>
                                <div class="d-flex align-items-center mb-3">
                                    <div class="subheader">Barcodes</div>
                                </div>
                                <div class="h1">33</div>
                            </div>
                        </a>
                    </div>
                </div>
                
                
                <div class="col-sm-6 col-lg-3">
                    <div class="card">
                        <a href="{% url 'polls:create_qr' %}">
                            <div class="card-stamp">
                                <div class="card-stamp-icon bg-green">
                                    <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-users"
                                        width="24" height="24" viewBox="0 0 24 24" stroke-width="2"
                                        stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                        <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                                        <circle cx="9" cy="7" r="4"></circle>
                                        <path d="M3 21v-2a4 4 0 0 1 4 -4h4a4 4 0 0 1 4 4v2"></path>
                                        <path d="M16 3.13a4 4 0 0 1 0 7.75"></path>
                                        <path d="M21 21v-2a4 4 0 0 0 -3 -3.85"></path>
                                    </svg>
                                </div>
                            </div>
                            <div class="card-body">
                                <div class="d-flex align-items-center mb-3">
                                    <div class="subheader">Overall Users</div>
                                </div>
                                <div class="h1">1</div>
                            </div>
                        </a>
                    </div>
                </div>

                
                <div class="col-sm-8 col-lg-8">
                    <div class="card">
                        <div class="card-body">
                            <div class="d-flex align-items-center mb-3">
                                <div class="subheader mb-2">Month Wise Generated QR and Barcodes</div>
                            </div>
                            <div class="row">
                                <div class="col">
                                    <div id="thisMonth"></div>
                                </div>
                                <div class="col-md-auto">
                                    <div class="divide-y divide-y-fill">
                                        <div class="px-3">
                                            <div>
                                                <span class="status-dot bg-red"></span> QR codes
                                            </div>
                                            <div class="h2">
                                                95</div>
                                        </div>
                                        <div class="px-3">
                                            <div>
                                                <span class="status-dot bg-orange"></span> EPC QR codes
                                            </div>
                                            <div class="h2">1</div>
                                        </div>
                                        <div class="px-3">
                                            <div>
                                                <span class="status-dot bg-green"></span> Barcodes
                                            </div>
                                            <div class="h2">33</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                
                <div class="col-md-4 col-xl-4">
                    <div class="card">
                        <div class="card-body">
                            
                            <div class="d-flex align-items-center mb-3">
                                <div class="subheader mb-2">Generated QR and Barcodes</div>
                            </div>
                            <div id="overAll"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    
    
</div>


    </div>

    <!-- Scripts -->

<script>
    // This Month Overview
    // @formatter:off
	document.addEventListener("DOMContentLoaded", function () {
        "use strict";
		window.ApexCharts && (new ApexCharts(document.getElementById('thisMonth'), {
			chart: {
				type: "line",
				fontFamily: 'inherit',
				height: 212,
				parentHeightOffset: 0,
				toolbar: {
					show: false,
				},
				animations: {
					enabled: false
				},
			},
			fill: {
				opacity: 1,
			},
			stroke: {
				width: 2,
				lineCap: "round",
				curve: "smooth",
			},
			series: [{
				name: `QR codes`,
				data: [43,49,3,0,0,0,0,0,0,0,0,0]
			},{
				name: `EPC QR codes`,
				data: [1,0,0,0,0,0,0,0,0,0,0,0]
			},{
				name: `Barcodes`,
				data: [18,14,1,0,0,0,0,0,0,0,0,0]
			}],
			tooltip: {
				theme: 'dark'
			},
			grid: {
				padding: {
					top: -20,
					right: 0,
					left: -4,
					bottom: -4
				},
				strokeDashArray: 4,
			},
			xaxis: {
				labels: {
					padding: 0,
				},
				tooltip: {
					enabled: false
				},
				type: 'year',
			},
			yaxis: {
				labels: {
					padding: 4,
				},
			},
			labels: [`Jan`, `Feb`, `Mar`, `Apr`, `May`, `Jun`, `July`, `Aug`, `Sept`, `Oct`, `Nov`, `Dec`],
			colors: ["#d63939", "#F76707", "#2FB344"],
			legend: {
				show: false,
			},
		})).render();
	});
	// @formatter:on

    // Overall
    // @formatter:off
    document.addEventListener("DOMContentLoaded", function () {
        "use strict";
      	window.ApexCharts && (new ApexCharts(document.getElementById('overAll'), {
      		chart: {
      			type: "donut",
      			fontFamily: 'inherit',
      			height: 250,
      			sparkline: {
      				enabled: true
      			},
      			animations: {
      				enabled: false
      			},
      		},
      		fill: {
      			opacity: 1,
      		},
      		series: [95, 1, 33],
      		labels: ['QR codes', 'EPC QR codes', 'Barcodes'],
      		tooltip: {
      			theme: 'dark'
      		},
      		grid: {
      			strokeDashArray: 4,
      		},
      		colors: ["#d63939", "#F76707", "#2FB344"],
      		legend: {
      			show: true,
      			position: 'bottom',
      			offsetY: 12,
      			markers: {
      				width: 10,
      				height: 10,
      				radius: 100,
      			},
      			itemMargin: {
      				horizontal: 8,
      				vertical: 8
      			},
      		},
      		tooltip: {
      			fillSeriesColor: false
      		},
      	})).render();
    });
    // @formatter:on
</script>

templates/footer.html
<footer class="footer footer-transparent d-print-none">
    <div class="container">
        <div class="row text-center align-items-center flex-row-reverse">
            <div class="col-12 col-lg-auto mt-3 mt-lg-0">
                <ul class="list-inline list-inline-dots mb-0">
                    <li class="list-inline-item">
                    <span id="year"></span>
                        <a href="{% url 'polls:index' %}" class="link-secondary">Analiz Qr
                            <strong>v1.0.0</strong></a>.
                        
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>

templates/header.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <title>QR</title>

            <!-- Favicon -->
        <link rel="icon" href="https://qrlite.nativecode.in/images/favicon.png" sizes="96x96" type="image/png" />
    
    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap">

    <!-- CSS files -->
  
    <link href="{% static 'css/tabler-flags.min.css' %} " rel="stylesheet" />   
    <link href="{% static 'css/tabler-payments.min.css' %} " rel="stylesheet" />   
    <link href="{% static 'css/tabler.min.css' %} " rel="stylesheet" />   
    <link href="{% static 'css/tabler-vendors.min.css' %} " rel="stylesheet" />
    <link href="{% static 'css/demo.min.css' %}" rel="stylesheet" />
    <link rel="stylesheet" href="{% static 'css/dataTables.bootstrap4.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">

 <!-- Scripts -->
 <script type="text/javascript" src="{% static 'js/jquery.min.js' %} "></script>
 <script type="text/javascript" src="{% static 'js/sweetalert.min.js' %} "></script>
 <script type="text/javascript" src="{% static 'js/chart.js' %} "></script>

 
 </head>
 <body class="antialiased" data-bs-theme="light" dir="ltr">
    <div class="page page-center preloader-wrapper">
        <div class="container container-slim py-4">
            <div class="text-center">
                <div class="mb-3">
                    <img src="{% static 'images/favicon.png' %}" height="36" alt="QR Analiz">
                </div>
                <div class="mb-3 h3">Loading</div>
                <div class="progress progress-sm">
                    <div class="progress-bar progress-bar-indeterminate bg-green"></div>
                </div>
            </div>
        </div>
    </div>

    <div id="wrapper" class="page">
        
        <header class="navbar navbar-expand-md navbar-light d-print-none">
    <div class="container-xl">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar-menu">
            <span class="navbar-toggler-icon"></span>
        </button>
        <h1 class="navbar-brand navbar-brand-autodark d-none-navbar-horizontal pe-0 pe-md-3">
            <a href="{% url 'polls:index' %}">
                <img src="{% static 'images/qr-code-area-3d-illustration_118019-6256.jpg' %} " width="200" height="50" alt="QR Analiz"
                    class="navbar-brand-image custom-logo">
            </a>
        </h1>
        <div class="navbar-nav flex-row order-md-last">

            
                            <div class="nav-item dropdown mx-2">
                    <div class="lang">
                        <select type="text" class="form-select small-btn" placeholder="Select a language"
                            id="chooseLang" value="">
                                                            
                            <option value="az">
                                <strong>Aze</strong></option>
                                   
                                                            <option value="ru">
                                    <strong>Rus</strong></option>
                                                        
                                   
                                                            <option value="eng">
                                    <strong>Eng</strong></option>
                                                
                                    
                                                    </select>
                    </div>
                </div>
            
            
            <div class="nav-item dropdown">
                <a href="#" class="nav-link d-flex lh-1 text-reset p-0" data-bs-toggle="dropdown"
                    aria-label="Open user menu">
                    <span class="avatar">
                        <img src="{% static 'images/profile.png' %}"
                            alt="Administrator">
                    </span>
                    <div class="d-none d-xl-block ps-2">
                        <div>Administrator</div>
                        <div class="mt-1 small text-muted">Administrator</div>
                    </div>
                </a>
                <div class="dropdown-menu dropdown-menu-end dropdown-menu-arrow">
                    <a href=""
                        class="dropdown-item">Profile &amp; account</a>
                    
                    <a href="" class="dropdown-item hide-theme-dark"
                        data-bs-placement="bottom">
                        Dark mode
                    </a>
                    <a href="" class="dropdown-item hide-theme-light"
                        data-bs-placement="bottom">
                        Light mode
                    </a>
                    <a href="logout" class="dropdown-item"
                        >Logout</a>
                    
                </div>
            </div>

        </div>
    </div>
</header>
 {% block body %}

 {%endblock%}

 <script type="text/javascript" src="{% static 'js/apexcharts.min.js' %} "></script>
 <script type="text/javascript" src="{% static 'js/main.js' %} "></script>
 <script type="text/javascript" src="{% static 'js/dataTables.bootstrap4.min.js' %} "></script>
 <script type="text/javascript" src="{% static 'js/jquery.dataTables.min.js' %} "></script>
 <script type="text/javascript" src="{% static 'js/tabler.min.js' %} "></script>
</body>

</html>

templates/main.html
{% extends 'header.html' %}
{% block body %}
      {% load static %}
      
      {% include 'dashboard.html' %}








      {% include 'footer.html' %}

    {% endblock %}

templates/navbar.html
<div class="navbar-expand-md">
    <div class="collapse navbar-collapse" id="navbar-menu">
        <div class="navbar navbar-light">
            <div class="container-xl">
                <ul class="navbar-nav">
                    
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'polls:index' %}">
                            <span class="nav-link-icon d-md-none d-lg-inline-block">
                                <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24"
                                    viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none"
                                    stroke-linecap="round" stroke-linejoin="round">
                                    <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                                    <polyline points="5 12 3 12 12 3 21 12 19 12" />
                                    <path d="M5 12v7a2 2 0 0 0 2 2h10a2 2 0 0 0 2 -2v-7" />
                                    <path d="M9 21v-6a2 2 0 0 1 2 -2h2a2 2 0 0 1 2 2v6" />
                                </svg>
                            </span>
                            <span class="nav-link-title">
                                Dashboard
                            </span>
                        </a>
                    </li>

                    
                                        <li 
                        class="nav-item dropdown ">
                        <a class="nav-link dropdown-toggle" href data-bs-toggle="dropdown"
                            data-bs-auto-close="outside" role="button" aria-expanded="false">
                            <span class="nav-link-icon d-md-none d-lg-inline-block">
                                <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-id"
                                    width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor"
                                    fill="none" stroke-linecap="round" stroke-linejoin="round">
                                    <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                                    <rect x="3" y="4" width="18" height="16" rx="3"></rect>
                                    <circle cx="9" cy="10" r="2"></circle>
                                    <line x1="15" y1="8" x2="17" y2="8"></line>
                                    <line x1="15" y1="12" x2="17" y2="12"></line>
                                    <line x1="7" y1="16" x2="17" y2="16"></line>
                                </svg>
                            </span>
                            <span class="nav-link-title">
                                QR Codes
                            </span>
                        </a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="{% url 'polls:qr_lists' %}">
                                QR Codes
                            </a>
                            <a class="dropdown-item" href="{% url 'polls:create_qr' %}">
                                Create QR Codes
                            </a>
                        </div>
                    </li>
                    
                                        
                    <li
                        class="nav-item dropdown ">
                        <a class="nav-link dropdown-toggle" href data-bs-toggle="dropdown"
                            data-bs-auto-close="outside" role="button" aria-expanded="false">
                            <span class="nav-link-icon d-md-none d-lg-inline-block">
                                <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-id"
                                    width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor"
                                    fill="none" stroke-linecap="round" stroke-linejoin="round">
                                    <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                                    <rect x="3" y="4" width="18" height="16" rx="3"></rect>
                                    <circle cx="9" cy="10" r="2"></circle>
                                    <line x1="15" y1="8" x2="17" y2="8"></line>
                                    <line x1="15" y1="12" x2="17" y2="12"></line>
                                    <line x1="7" y1="16" x2="17" y2="16"></line>
                                </svg>
                            </span>
                            <span class="nav-link-title">
                                Barcodes
                            </span>
                        </a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="{% url 'polls:barcode_view' %}">
                                Barcodes
                            </a>
                            <a class="dropdown-item" href="{% url 'polls:create_barcode' %}">
                                Create Barcodes
                            </a>
                        </div>
                    </li>
                    


                    
                  

                </ul>
            </div>
        </div>
    </div>
</div>